dist: trusty
sudo: required
services:
  - docker
language: python
python:
  - "2.7"
  - "3.5"
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements-dev.txt
script:
  - coverage run -m py.test && coveralls
