language: python
sudo: required
services:
  - docker
env:
  matrix:
  - PYTHON_VERSION=2 TENSORFLOW_VERSION=1.8
  - PYTHON_VERSION=3 TENSORFLOW_VERSION=1.8
install:
  - docker pull "haowenxu/travis-tensorflow-docker:py${PYTHON_VERSION}tf${TENSORFLOW_VERSION}"
script:
  - docker run
      -v "$(pwd)":"$(pwd)"
      -w "$(pwd)"
      -e TRAVIS="${TRAVIS}"
      -e TRAVIS_JOB_ID="${TRAVIS_JOB_ID}"
      -e TRAVIS_BRANCH="${TRAVIS_BRANCH}"
      "haowenxu/travis-tensorflow-docker:py${PYTHON_VERSION}tf${TENSORFLOW_VERSION}"
      bash -c "pip install -r requirements-dev.txt && coverage run -m py.test && coveralls"
